# Generated by Django 6.1.1 on 2026-09-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('first', 'Первый класс')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('time_limit', models.IntegerField(default=60, help_text='Лимит времени в секундах')),
                ('xp_reward', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('node_type', models.CharField(choices=[('dialog', 'Диалог'), ('choice', 'Выбор действия'), ('timer', 'Таймер'), ('result', 'Результат')], default='dialog', max_length=20)),
                ('text', models.TextField(help_text='Текст диалога или описания ситуации')),
                ('speaker', models.CharField(default='NPC', help_text='Кто говорит: NPC, Проводник, Система', max_length=50)),
                ('time_limit', models.IntegerField(blank=True, help_text='Таймер для этого узла (сек)', null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст варианта ответа')),
                ('loyalty_change', models.IntegerField(default=0, help_text='Изменение лояльности пассажира')),
                ('safety_change', models.IntegerField(default=0, help_text='Изменение рейтинга безопасности')),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_optimal', models.BooleanField(default=False, help_text='Оптимальный выбор для обучения')),
                ('feedback', models.TextField(blank=True, help_text='Обратная связь после выбора')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='scenarios.scenarionode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='scenarios.scenarionode')),
            ],
        ),
    ]
